import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Fraunces,
  DM_Serif_Display,
  Playfair_Display,
  Cormorant_Garamond,
  Inter,
  Manrope,
  Archivo,
  Source_Serif_4,
} from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  variable: "--font-text",
  subsets: ["latin"],
});

const fraunces = Fraunces({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["400"],
});





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${fraunces.variable} ${manrope.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
